
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treelogy-model-microservice-server
  namespace: treelogy-commons
  labels:
    app: treelogy-model-microservice-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: treelogy-model-microservice-api
  template:
    metadata:
      labels:
        app: treelogy-model-microservice-api
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: treelogy-model-microservice-api
          image: cezarfelps/treelogy-model-microservice:latest
          ports:
            - containerPort: 81

---
kind: Service
apiVersion: v1
metadata:
  name: treelogy-model-microservice-service
  namespace: treelogy-commons
spec:
  selector:
    app: treelogy-model-microservice-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: treelogy-commons
  name: treelogy-model-microservice-ingress
  annotations:
    allow.http: "false"
spec:
  rules:
    - host: treelogy-model-microservice.rancher.treelogy.eco.br
      http:
        paths:
          - path: /
            backend:
              serviceName: treelogy-model-microservice-service
              servicePort: 81