pipeline{
    agent any
    environment {
    //Use Pipeline Utility Steps plugin to read information from pom.xml into env variables
    IMAGE = readMavenPom().getArtifactId()
    VERSION = readMavenPom().getVersion()
    }
    stages{
        stage ('Build Backend'){
            steps{
                sh 'echo Build do Backend'
                sh 'mvn install'
            }
        }
        stage ('Unit Tests'){
            steps{
                sh 'echo Unit Tests'
                sh 'mvn test'
            }
        }
        stage('Docker Build Image') {
              steps {
                  script {
                      echo "${VERSION}"
                      echo "${IMAGE}"
                      dockerapp = docker.build("cezarfelps/treelogy-template-back:${env.BUILD_ID}",
                        '-f ./deploy/Dockerfile .')
                  }
              }
          }
      stage('Docker Push Image') {
          steps {
              script {
                      docker.withRegistry('https://registry.hub.docker.com', 'treelogy-docker-hub') {
                      dockerapp.push('latest')
                      dockerapp.push("${env.BUILD_ID}")
                  }
              }
          }
      }
        stage ('Update Deployment Kubernetes'){
          environment {
                tag = "${env.BUILD_ID}"
            }
            steps{
                sh 'sed -i "s/{{tag}}/${tag} /g" deploy/deployment.yaml'
                sh 'cat deploy/deployment.yaml'
            }
        }
    }
}
