name: jenkins-CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        uses: treelogysystem/treelogy-template-back@master
        with:
          url: http://jenkins.treelogy.eco.br/
          job_name: treelogy-template-back
          username: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          timeout: "1000"
