# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - id: triggerjenkinsjob
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server:  "118f3cbcdfbdeccb488bbb579ce7e9c79d" # URL of the jenkins server. ex: http://myjenkins.acme.com:8080
          jenkins-job: "treelogy-template-backend" # The name of the jenkins job to run
          jenkins-username: "github" # user name for accessing jenkins
          jenkins-pat: "118f3cbcdfbdeccb488bbb579ce7e9c79d" # personal Access token for accessing Jenkins
          poll-time: 10 # how often (seconds) to poll the jenkins server for results
          timeout-value: 600 # How long (seconds) to poll before timing out the action
          verbose: true # true/false - turns on extra logging
