# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:

      - name: Test
        uses: actions/github-script@0.3.0
        with:
          github-token: "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"
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);

      - name: trigger jenkins job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://jenkins.treelogy.eco.br"
          user: "github"
          token: "118f3cbcdfbdeccb488bbb579ce7e9c79d"
          job: "treelogy-template-backend"

      - name: Trigger jenkins job
        uses: joshlk/jenkins-githubaction@master
        with:
          url: "http://jenkins.treelogy.eco.br"
          job_name: "treelogy-template-backend"
          username: "github"
          api_token: "118f3cbcdfbdeccb488bbb579ce7e9c79d"
          timeout: "1000"

      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}