name: Your GHA
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  your_job_name:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger your-awesome-job-name job
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: "http://jenkins.treelogy.eco.br/"
          jenkins_user: "github"
          jenkins_token: "118f3cbcdfbdeccb488bbb579ce7e9c79d"
          proxy: "https://github.com/treelogysystem/treelogy-template-back/"
          job_name: "treelogy-template-backend"
          job_timeout: "3600" # Default 30 sec. (optional)